version: "3"
services:
  album-front:
    image: ${IMAGE}:latest
    container_name: ${CONTAINER_NAME}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    extra_hosts:
      - db.hive-ltd.com:${DB_HOST}