version: "3"
services:
  api:
    image: ${IMAGE}:latest
    container_name: ${CONTAINER_NAME}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    extra_hosts:
      - db.tuboshu.io:${DB_HOST}
      - redis.tuboshu.io:${DB_HOST}
