definitions:
  app.Response:
    properties:
      code:
        type: integer
      data:
        type: object
      msg:
        type: string
    type: object
  models.User:
    properties:
      avatar_src:
        description: 头像地址
        type: string
      company:
        description: 公司
        type: string
      created_on:
        type: integer
      deleted_on:
        type: integer
      description:
        description: 描述
        type: string
      email:
        description: 电子邮件
        type: string
      id:
        type: integer
      modified_on:
        type: integer
      name:
        description: 昵称
        type: string
      password:
        description: 密码
        type: string
      position:
        description: 职位
        type: string
      sex:
        description: 性别
        type: integer
      username:
        description: 用户名
        type: string
      web_site:
        description: 网站
        type: string
    type: object
  router.auth:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
info:
  contact: {}
  description: Tuboshu Service Api
  license: {}
  termsOfService: https://github.com/opensourceai
  title: Tuboshu Service Api
  version: "2.0"
paths:
  /auth/login:
    post:
      parameters:
      - description: user
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/router.auth'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: 获取认证信息
      tags:
      - Auth
  /auth/register:
    post:
      parameters:
      - description: user
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: 添加用户
      tags:
      - Auth
  /router/v1/tags/import:
    post:
      parameters:
      - description: Image File
        in: formData
        name: image
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: Import Image
swagger: "2.0"
